// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "progressTimeout": number;
      "styleEditorAssetsVersion": string;
      "citationDialogInitialCollectionMode": string;
      "citationDialogCollectionTreeWidth": number;
      "serverAuthToken": string;
      "serverTrustedOrigins": string;
      "debugLoggingEnabled": boolean;
      "debugLoggingModules": string;
      "debugLoggingDesktopAutoExport": boolean;
    };
  }
}
