#!/usr/bin/env node
/*
  Generate typings/i10n.d.ts from addon/locale/**.ftl
  - Collects all unique Fluent message IDs across locales
  - Sorts them alphabetically
  - Writes a union type `FluentMessageId`
*/
import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const REPO_ROOT = path.resolve(__dirname, '..');
const LOCALE_DIR = path.join(REPO_ROOT, 'addon', 'locale');
const OUTPUT_FILE = path.join(REPO_ROOT, 'typings', 'i10n.d.ts');

async function listFilesRecursive(dir) {
  const out = [];
  const entries = await fs.readdir(dir, { withFileTypes: true });
  for (const e of entries) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) {
      out.push(...(await listFilesRecursive(p)));
    } else if (e.isFile() && e.name.endsWith('.ftl')) {
      out.push(p);
    }
  }
  return out;
}

function extractIds(ftlContent) {
  const ids = new Set();
  const lines = ftlContent.split(/\r?\n/);
  for (const raw of lines) {
    const line = raw.trim();
    if (!line) continue;
    if (line.startsWith('#')) continue; // comments
    if (line.startsWith('.')) continue; // attributes
    // Match message IDs of the form: id = ...
    const m = line.match(/^([a-z0-9][a-z0-9\-]*)\s*=/i);
    if (m) ids.add(m[1].toLowerCase());
  }
  return ids;
}

function renderTypings(ids) {
  const sorted = Array.from(ids).sort();
  const header = `// Generated by zotero-plugin-scaffold\n/* prettier-ignore */\n/* eslint-disable */\n// @ts-nocheck\n`;
  const typeLines = sorted.map((id) => `  | '${id}'`).join('\n');
  return `${header}export type FluentMessageId =\n${typeLines};\n`;
}

async function main() {
  const files = await listFilesRecursive(LOCALE_DIR);
  const idSet = new Set();
  for (const f of files) {
    const content = await fs.readFile(f, 'utf8');
    for (const id of extractIds(content)) idSet.add(id);
  }
  const output = renderTypings(idSet);
  await fs.writeFile(OUTPUT_FILE, output, 'utf8');
  console.log(`Updated ${path.relative(REPO_ROOT, OUTPUT_FILE)} with ${idSet.size} ids from ${files.length} files.`);
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
