#!/usr/bin/env node

import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, "..");

const schemaPath = path.join(
  repoRoot,
  "dev",
  "Zotero-Source",
  "resource",
  "schema",
  "global",
  "schema.json",
);
const outPath = path.join(repoRoot, "typings", "item.d.ts");

// Banyan citation dialog only operates on Zotero "regular items".
// Zotero.Item.prototype.isRegularItem() is false for note/attachment/annotation.
const EXCLUDED_ITEM_TYPES = new Set(["note", "attachment", "annotation"]);

// Banyan focuses on citation generation; these fields are dropped from the simplified item.
// Keep in sync with src/utils/item.ts
const EXCLUDED_FIELDS = new Set([
  "version",
  "abstractNote",
  "collections",
  "dateAdded",
  "dateModified",
  "notes",
]);

function uniq(arr) {
  return Array.from(new Set(arr));
}

function pascalCase(input) {
  // Keep alphanumerics; split camelCase + separators
  const s = String(input || "");
  const parts = s
    .replace(/([a-z0-9])([A-Z])/g, "$1 $2")
    .replace(/[^a-zA-Z0-9]+/g, " ")
    .trim()
    .split(/\s+/g)
    .filter(Boolean);
  return parts
    .map((p) => p.slice(0, 1).toUpperCase() + p.slice(1))
    .join("");
}

function interfaceNameForItemType(itemType) {
  return `${pascalCase(itemType)}Item`;
}

function quoteUnion(values) {
  return values.map((v) => JSON.stringify(v)).join("\n  | ");
}

function formatStringProps(fieldNames) {
  return fieldNames
    .filter((f) => f !== "itemType")
    .map((f) => `  ${f}?: string;`)
    .join("\n");
}

function extractFieldNames(typeDef) {
  const rawFields = Array.isArray(typeDef.fields) ? typeDef.fields : [];
  const names = [];
  for (const f of rawFields) {
    if (!f || typeof f !== "object") continue;
    // Prefer concrete field, but keep baseField if field absent
    const field = typeof f.field === "string" ? f.field : null;
    const baseField = typeof f.baseField === "string" ? f.baseField : null;
    if (field) names.push(field);
    else if (baseField) names.push(baseField);
  }

  // These are commonly present in toJSON but not guaranteed in schema fields.
  // Keep them on ItemBase.
  return uniq(names).sort();
}

function extractCreatorTypes(typeDef) {
  const raw = Array.isArray(typeDef.creatorTypes) ? typeDef.creatorTypes : [];
  const types = [];
  for (const c of raw) {
    if (!c || typeof c !== "object") continue;
    if (typeof c.creatorType === "string" && c.creatorType) {
      types.push(c.creatorType);
    }
  }
  return uniq(types).sort();
}

async function main() {
  const schemaText = await fs.readFile(schemaPath, "utf8");
  const schema = JSON.parse(schemaText);

  const itemTypeDefs = Array.isArray(schema.itemTypes) ? schema.itemTypes : [];
  const regularItemTypeDefs = itemTypeDefs.filter((d) => {
    const itemType = d && typeof d.itemType === "string" ? d.itemType : null;
    return Boolean(itemType) && !EXCLUDED_ITEM_TYPES.has(itemType);
  });
  const itemTypes = uniq(
    regularItemTypeDefs
      .map((d) => (d && typeof d.itemType === "string" ? d.itemType : null))
      .filter(Boolean),
  ).sort();

  const creatorTypeSet = new Set();
  for (const def of regularItemTypeDefs) {
    for (const ct of extractCreatorTypes(def)) {
      creatorTypeSet.add(ct);
    }
  }
  const creatorTypes = Array.from(creatorTypeSet).sort();

  const header = `// This file is generated by dev/genItemTypesFromSchema.mjs
//
// Source: dev/Zotero-Source/resource/schema/global/schema.json
//
// Do not edit this file by hand. Re-run the generator instead.

`;

  const prelude = `export type ExtraValue = string | string[];
export type ExtraMap = Record<string, ExtraValue>;

export type CreatorType =
  | ${quoteUnion(creatorTypes)};

type CreatorPersonalName<T extends CreatorType = CreatorType> = {
  creatorType: T;
  firstName: string;
  lastName: string;
  name?: never;
};

type CreatorSingleName<T extends CreatorType = CreatorType> = {
  creatorType: T;
  firstName?: never;
  lastName?: never;
  name: string;
};

export type Creator<T extends CreatorType = CreatorType> =
  | CreatorPersonalName<T>
  | CreatorSingleName<T>;

export type ItemType =
  | ${quoteUnion(itemTypes)};

export type ItemBase<T extends ItemType = ItemType> = {
  key: string;
  itemType: T;

  id: number;
  uri: string;
  year?: string;
  firstCreator?: string;

  title?: string;
  date?: string;

  /** Tags (list of tag names). */
  tags?: string[];

  /** Relations (predicates -> URIs). */
  relations?: Record<string, string[]>;

  /** Raw creators from toJSON(). */
  creators: Creator[];

  /** Parsed from Zotero's string \`extra\` field (\"key: value\" per line). */
  extra?: ExtraMap;

  /** Other fields from Zotero.Item.toJSON() */
  [field: string]: string;
};

`;

  const perTypeInterfaces = [];
  const unionMembers = [];

  for (const itemType of itemTypes) {
    const def = regularItemTypeDefs.find((d) => d && d.itemType === itemType) || {};
    const iface = interfaceNameForItemType(itemType);
    unionMembers.push(iface);

    const fields = extractFieldNames(def)
      // Common base fields already present on ItemBase
      .filter((f) => !["id", "key", "uri", "title", "date", "extra", "tags", "relations", "creators"].includes(f))
      // Fields intentionally excluded from Banyan item typings
      .filter((f) => !EXCLUDED_FIELDS.has(f));

    const creatorTypesForType = extractCreatorTypes(def);
    const creatorsLine = creatorTypesForType.length
      ? `\n  creators?: Creator<${quoteUnion(creatorTypesForType).replaceAll("\n  | ", " | ")}>[];`
      : "";

    const body = fields.length ? `\n${formatStringProps(fields)}` : "";

    perTypeInterfaces.push(
      `export type ${iface} = ItemBase<${JSON.stringify(itemType)}> & {${body}${creatorsLine}\n};\n`,
    );
  }

  const union = `export type Item =\n  | ${unionMembers.join("\n  | ")};\n`;

  const output = header + prelude + perTypeInterfaces.join("\n") + union;

  await fs.writeFile(outPath, output, "utf8");

   
  console.log(
    `[gen:item-types][info] Generated: ${path.relative(repoRoot, outPath)} | itemTypes: ${itemTypes.length} | creatorTypes: ${creatorTypes.length}`
  );
}

main().catch((err) => {
  console.error('[gen:item-types][error]', err && err.message ? err.message : err);
  if (err && err.stack) {
    console.error('[gen:item-types][error][stack]', err.stack);
  }
  process.exitCode = 1;
});
